### ISSUE TITLE
problam after deploy

### ISSUE THREAD

**Issue by wangyu1997** [IQSS/dataverse-docker#12] opened 2018-11-20 13:32 UTC
helle i just deploy dv,but the glassfish seems to show the default page
![873a4692-9cc0-47e7-8407-6f89e51d16e4](https://user-images.githubusercontent.com/15991233/48776804-c1fff380-ed0b-11e8-8441-3e833c0e653a.png)

**Comment by 4tikhonov** [comment] 2018-11-20 13:35
Can you pull the latest version, it was just fixed in https://github.com/IQSS/dataverse-docker/issues/10?

**Comment by wangyu1997** [comment] 2018-11-20 13:42
i know the bro fixed it moments ago, and my version has contained his code, but it doesn't work any way... can you help me ?

**Comment by MrK191** [comment] 2018-11-20 13:56
Have you tried to do docker system prune --volumes? Because otherwise it will just used what was before. I can confirm that it works on clean system, I used the docker there.

**Comment by wangyu1997** [comment] 2018-11-20 14:09
ok . i will try it ,thks

**Comment by wangyu1997** [comment] 2018-11-21 02:07
hello I tried today. but got the same problem . always shows glassfish default page.

**Comment by wangyu1997** [comment] 2018-11-21 02:39
@pdurbin hello . I must install with docked . I tried this but when I deploy the dv manually it throws the error that cannot connect local host:4848. Is any service start failed?

**Comment by pdurbin** [comment] 2018-11-21 02:48
@wangyu1997 I don't think Dataverse is quite ready to run in Docker for production. Please see https://github.com/IQSS/dataverse/issues/4665

If you're interested in running Dataverse in Docker for development purposes, that's fine. Some developers run the integration test suite in Docker. Please see http://guides.dataverse.org/en/4.9.4/developers/testing.html#running-the-full-api-test-suite-using-docker

Maybe you can tell us a little more about your goals. We'd love to help you get Dataverse installed.

**Comment by wangyu1997** [comment] 2018-11-21 02:53
@pdurbin thanks!  We want to deploy the dv as our data center . And I just want to deploy with no change. Maybe I meet some pro and if you can help me we can chat with email or fb . Emergency!

**Comment by pdurbin** [comment] 2018-11-21 02:59
@wangyu1997 by "no change" I assume you mean you don't want to fork the code. You want it to just work. That's fine. As we say at https://dataverse.org/contact installation questions can be directed to support@dataverse.org but you will probably be advised to perform a traditional installation rather than the fancy new Docker and Kubernetes stuff in this repo, which is community-supported.

**Comment by wangyu1997** [comment] 2018-11-21 03:18
@pdurbin nonono I mean we want to deploy it with no change by now because we have a lot of data to store . And we meet to do some extra works to integrate it into our project

**Comment by wangyu1997** [comment] 2018-11-21 05:04
@pdurbin  sorry to brother you , I just came back , you can see the pic below . i think there must be some problems with connection while deploying 
![f7d097c5-7f4b-4aaf-87bf-ca4bef20a2ba](https://user-images.githubusercontent.com/15991233/48820029-ea303680-ed8d-11e8-826e-0734566adda2.png)

**Comment by wangyu1997** [comment] 2018-11-21 05:10
@pdurbin  i am confused with this ?  when deploying dv it tells me that connect to 4848 failed. and the the glassfish started at port 4848 . shouldn't it start before?
![f7d097c5-7f4b-4aaf-87bf-ca4bef20a2ba](https://user-images.githubusercontent.com/15991233/48820181-c1f50780-ed8e-11e8-86e6-d66053b9086b.png)

**Comment by wangyu1997** [comment] 2018-11-21 05:30
@MrK191  hey I tried
>/usr/local/glassfish4/bin/asadmin deploy deps/dataverse.war   
but get
```
Remote server does not listen for requests on [localhost:4848]. Is the server up?
Unable to get remote commands. 
Closest matching local command(s): 
    help

Command deploy failed.
```

**Comment by wangyu1997** [comment] 2018-11-21 05:36
@pdurbin  it seems that the glassfish will auto close ... 
![d1a8bae9-be16-47aa-a585-be77bedce4be](https://user-images.githubusercontent.com/15991233/48821029-80665b80-ed92-11e8-968c-f4ee2f3d95b9.png)

**Comment by MrK191** [comment] 2018-11-21 09:32
@wangyu1997 @4tikhonov 
The problem that is here is not related to the issue #10, You should try to fix glassfish deployment  problem without the docker first, since I don't think docker is the problem here.

**Comment by wangyu1997** [comment] 2018-11-21 10:37
@MrK191 sort I don’t understand what you mean . I just pull the latest version and clean all my docker cache and images and rebuild the DV.  First Postgres then sole . When I start dataverse . I wait long time while it deploy the war . Then it seems that the glass fish admin has down. Throws the error that Cabot connect to local host:4848 is server up . Like the picture above. And then deploy failed . Network error.

**Comment by brndgtl** [comment] 2019-03-08 16:09
No point creating a new ticket. I'm also having the same issue with the latest version on a clean deployment of dv @4tikhonov

**Comment by pdurbin** [comment] 2019-03-08 16:51
@brndgtl thanks for confirming that you're seeing the same problem. I'd like to mention that there is another community effort toward running Dataverse in Docker (docker-kubernetes) and the author has asked for feedback at https://github.com/IQSS/dataverse/issues/4665#issuecomment-467446353

**Comment by 4tikhonov** [comment] 2019-03-08 17:08
Hi all, just one remark: our current version isn't up-to-date mainly because CESSDA DataverseEU project was finished in December and new SSHOC project will officially start in the middle of March, so there are not so much maintenance efforts to get it upgraded to the latest version.

@brndgtl, we'll take a look and I'll get back to you.

**Comment by 4tikhonov** [comment] 2019-03-14 09:29
This issues fixed now and should work.

**Closed by 4tikhonov** 2019-03-14 09:29 UTC

**Comment by benzaked** [comment] 2019-11-12 08:48
Hey, I have the same issue. admin port isn't reachable (port 4848). did anyone know what I should do? 
@pdurbin 4tikhonov

**Comment by pdurbin** [comment] 2019-11-12 12:29
@benzaked I'm not sure. @4tikhonov or @MrK191 or @poikilotherm might have some ideas for you.
